# Generated by Django 3.0.3 on 2020-05-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptest', '0002_auto_20200505_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='image',
            field=models.FileField(upload_to='media/images/%Y/%m/%d'),
        ),
    ]
