# Generated by Django 3.0.3 on 2020-05-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uptest', '0003_auto_20200505_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='image',
        ),
    ]
